#!/bin/sh

# Не забыть сделать файл исполняемым
# Авто добавление названия ветки к сообщению в коммите.
#
NAME=$(git branch | grep '*' | sed 's/* //') 

if [ "$NAME" != 'master' ] 
then
  echo "https://trello.com/c/$NAME/"': '$(cat "$1") > "$1"
fi
