#!/bin/sh
#
# Automatically adds branch name and branch description to every commit message.
#
NAME=$(git branch | grep '*' | sed 's/* //') 

echo "$1"
if [ "$NAME" = 'master' ] 
then
  #
else
  echo "$NAME"': '$(cat "$1") > "$1"
fi





